/* Generated by tools/generate_logos_kana_zmk.py. Do not edit manually. */

#pragma once

#define LOGOS_KANA_KEY_NONE 0xFF

#define LOGOS_KANA_KEY_Q           0
#define LOGOS_KANA_KEY_W           1
#define LOGOS_KANA_KEY_E           2
#define LOGOS_KANA_KEY_R           3
#define LOGOS_KANA_KEY_T           4
#define LOGOS_KANA_KEY_Y           5
#define LOGOS_KANA_KEY_U           6
#define LOGOS_KANA_KEY_I           7
#define LOGOS_KANA_KEY_O           8
#define LOGOS_KANA_KEY_P           9
#define LOGOS_KANA_KEY_A           10
#define LOGOS_KANA_KEY_S           11
#define LOGOS_KANA_KEY_D           12
#define LOGOS_KANA_KEY_F           13
#define LOGOS_KANA_KEY_G           14
#define LOGOS_KANA_KEY_H           15
#define LOGOS_KANA_KEY_J           16
#define LOGOS_KANA_KEY_K           17
#define LOGOS_KANA_KEY_L           18
#define LOGOS_KANA_KEY_SEMI        19
#define LOGOS_KANA_KEY_Z           20
#define LOGOS_KANA_KEY_X           21
#define LOGOS_KANA_KEY_C           22
#define LOGOS_KANA_KEY_V           23
#define LOGOS_KANA_KEY_B           24
#define LOGOS_KANA_KEY_N           25
#define LOGOS_KANA_KEY_M           26
#define LOGOS_KANA_KEY_COMMA       27
#define LOGOS_KANA_KEY_DOT         28
#define LOGOS_KANA_KEY_SLASH       29

#define LOGOS_KANA_KEY_COUNT 30
