#!/usr/bin/env python3
import collections
import csv
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LAYOUT_CSV = ROOT / "data" / "my_kana_layout.csv"
ROMAJI_CSV = ROOT / "data" / "my_kana_romaji.csv"
OUT_DIR = ROOT / "config" / "my_kana" / "generated"

MACROS_OUT = OUT_DIR / "my_kana_macros.dtsi"
BEHAVIORS_OUT = OUT_DIR / "my_kana_behaviors_torabo_tsuki_lp.dtsi"
COMBOS_OUT = OUT_DIR / "my_kana_combos_torabo_tsuki_lp.dtsi"
LAYER_OUT = OUT_DIR / "my_kana_layer_torabo_tsuki_lp.dtsi"

TOTAL_POSITIONS = 66
KANA_TOGGLE_POSITION = 65
ROW_LENGTHS = [12, 12, 14, 14, 14]

EXPECTED_SINGLE_KEYS = 30
EXPECTED_COMBOS = 105
EXPECTED_TOTAL = 135

KEY_POSITIONS = {
    "q": 13,
    "w": 14,
    "e": 15,
    "r": 16,
    "t": 17,
    "y": 18,
    "u": 19,
    "i": 20,
    "o": 21,
    "p": 22,
    "a": 25,
    "s": 26,
    "d": 27,
    "f": 28,
    "g": 29,
    "h": 32,
    "j": 33,
    "k": 34,
    "l": 35,
    ";": 36,
    "z": 39,
    "x": 40,
    "c": 41,
    "v": 42,
    "b": 43,
    "n": 46,
    "m": 47,
    ",": 48,
    ".": 49,
    "/": 50,
}

LAYOUT_KEYCODES = {
    ";": "SEMI",
    ",": "COMMA",
    ".": "DOT",
    "/": "SLASH",
}

ROMAJI_KEYCODES = {
    "-": "MINUS",
    ",": "COMMA",
    ".": "DOT",
}

NAME_OVERRIDES = {
    "、": "comma",
    "。": "period",
    "ー": "long",
}


def read_csv(path, expected_headers):
    with path.open(newline="", encoding="utf-8") as file:
        reader = csv.DictReader(file)
        if reader.fieldnames != expected_headers:
            raise ValueError(f"{path}: expected headers {expected_headers}, got {reader.fieldnames}")
        rows = list(reader)

    for index, row in enumerate(rows, start=2):
        if any(value is None for value in row.values()):
            raise ValueError(f"{path}:{index}: malformed row {row}")
        for header in expected_headers:
            if header != "key2" and not row[header]:
                raise ValueError(f"{path}:{index}: {header} is required")
    return rows


def keycode_for_char(char):
    if re.fullmatch(r"[a-z]", char):
        return char.upper()
    if char in ROMAJI_KEYCODES:
        return ROMAJI_KEYCODES[char]
    raise ValueError(f"Unsupported romaji character: {char!r}")


def keycode_for_layout_key(key):
    if re.fullmatch(r"[a-z]", key):
        return key.upper()
    if key in LAYOUT_KEYCODES:
        return LAYOUT_KEYCODES[key]
    raise ValueError(f"Unsupported layout key: {key!r}")


def make_node_name(row, used_names):
    base = NAME_OVERRIDES.get(row["output"], row["romaji"])
    base = re.sub(r"[^a-z0-9]+", "_", base.lower()).strip("_")
    name = f"my_kana_{base}"
    if name not in used_names:
        used_names.add(name)
        return name

    suffix = 2
    while f"{name}_{suffix}" in used_names:
        suffix += 1
    name = f"{name}_{suffix}"
    used_names.add(name)
    return name


def validate_unique(rows, key_fn, label):
    duplicates = [item for item, count in collections.Counter(map(key_fn, rows)).items() if count > 1]
    if duplicates:
        raise ValueError(f"Duplicate {label}: {duplicates}")


def load_romaji():
    rows = read_csv(ROMAJI_CSV, ["output", "romaji"])
    validate_unique(rows, lambda row: row["output"], "romaji output")
    romaji = {row["output"]: row["romaji"] for row in rows}
    for output, value in romaji.items():
        for char in value:
            keycode_for_char(char)
    return romaji


def load_layout():
    rows = read_csv(LAYOUT_CSV, ["output", "key1", "key2"])
    validate_unique(rows, lambda row: row["output"], "layout output")
    validate_unique(rows, lambda row: (row["key1"], row["key2"]), "layout key combo")

    for index, row in enumerate(rows, start=2):
        for key_name in ["key1", "key2"]:
            key = row[key_name]
            if key and key not in KEY_POSITIONS:
                raise ValueError(f"{LAYOUT_CSV}:{index}: unknown {key_name} {key!r}")

    single_count = sum(not row["key2"] for row in rows)
    combo_count = sum(bool(row["key2"]) for row in rows)
    if len(rows) != EXPECTED_TOTAL or single_count != EXPECTED_SINGLE_KEYS or combo_count != EXPECTED_COMBOS:
        raise ValueError(
            "Unexpected layout counts: "
            f"total={len(rows)}, single={single_count}, combo={combo_count}"
        )
    return rows


def prepare_rows():
    romaji = load_romaji()
    rows = load_layout()

    missing = sorted({row["output"] for row in rows if row["output"] not in romaji})
    if missing:
        raise ValueError(f"Missing romaji mapping for: {', '.join(missing)}")

    used_names = set()
    for row in rows:
        row["romaji"] = romaji[row["output"]]
        row["node"] = make_node_name(row, used_names)
    return rows


def write_macros(rows):
    lines = [
        "// Generated by tools/generate_my_kana_zmk.py. Do not edit manually.",
        "",
    ]

    for row in rows:
        output_bindings = " ".join(f"&kp {keycode_for_char(char)}" for char in row["romaji"])
        lines.extend(
            [
                f"        {row['node']}: {row['node']} {{",
                '            compatible = "zmk,behavior-macro";',
                "            #binding-cells = <0>;",
                "            wait-ms = <MY_KANA_MACRO_WAIT_MS>;",
                "            tap-ms = <MY_KANA_MACRO_TAP_MS>;",
                f"            bindings = <{output_bindings}>;",
                "        };",
                "",
            ]
        )

        if row["key2"]:
            pass_bindings = " ".join(
                f"&kp {keycode_for_layout_key(key)}" for key in [row["key1"], row["key2"]]
            )
            lines.extend(
                [
                    f"        {row['node']}_pass: {row['node']}_pass {{",
                    '            compatible = "zmk,behavior-macro";',
                    "            #binding-cells = <0>;",
                    "            wait-ms = <MY_KANA_MACRO_WAIT_MS>;",
                    "            tap-ms = <MY_KANA_MACRO_TAP_MS>;",
                    f"            bindings = <{pass_bindings}>;",
                    "        };",
                    "",
                ]
            )

    MACROS_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_behaviors(rows):
    lines = [
        "// Generated by tools/generate_my_kana_zmk.py. Do not edit manually.",
        "",
    ]

    for row in rows:
        if row["key2"]:
            normal_binding = f"&{row['node']}"
            modified_binding = f"&{row['node']}_pass"
            behavior_name = f"{row['node']}_combo"
        else:
            normal_binding = f"&{row['node']}"
            modified_binding = f"&kp {keycode_for_layout_key(row['key1'])}"
            behavior_name = f"{row['node']}_key"

        lines.extend(
            [
                f"        {behavior_name}: {behavior_name} {{",
                '            compatible = "zmk,behavior-mod-morph";',
                "            #binding-cells = <0>;",
                f"            bindings = <{normal_binding}>, <{modified_binding}>;",
                "            mods = <MY_KANA_MODS>;",
                "            keep-mods = <MY_KANA_MODS>;",
                "        };",
                "",
            ]
        )

    BEHAVIORS_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_combos(rows):
    lines = [
        "// Generated by tools/generate_my_kana_zmk.py. Do not edit manually.",
        "",
    ]

    for row in rows:
        if not row["key2"]:
            continue
        pos1 = KEY_POSITIONS[row["key1"]]
        pos2 = KEY_POSITIONS[row["key2"]]
        lines.extend(
            [
                f"        combo_{row['node']} {{",
                "            timeout-ms = <MY_KANA_COMBO_TIMEOUT_MS>;",
                f"            key-positions = <{pos1} {pos2}>;",
                "            layers = <KANA>;",
                f"            bindings = <&{row['node']}_combo>;",
                "        };",
                "",
            ]
        )

    COMBOS_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_layer(rows):
    bindings = ["&trans"] * TOTAL_POSITIONS
    for row in rows:
        if row["key2"]:
            continue
        bindings[KEY_POSITIONS[row["key1"]]] = f"&{row['node']}_key"

    bindings[KANA_TOGGLE_POSITION] = "&my_kana_off"

    offset = 0
    layer_rows = []
    for row_length in ROW_LENGTHS:
        row_bindings = bindings[offset : offset + row_length]
        layer_rows.append(" ".join(f"{binding:<20}" for binding in row_bindings).rstrip())
        offset += row_length

    if offset != TOTAL_POSITIONS:
        raise ValueError(f"ROW_LENGTHS add up to {offset}, expected {TOTAL_POSITIONS}")

    lines = [
        "// Generated by tools/generate_my_kana_zmk.py. Do not edit manually.",
        "",
        "        kana_layer {",
        '            display-name = "Kana";',
        "            bindings = <",
    ]
    lines.extend(layer_rows)
    lines.extend(["            >;", "        };", ""])
    LAYER_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    rows = prepare_rows()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    write_macros(rows)
    write_behaviors(rows)
    write_combos(rows)
    write_layer(rows)
    print(
        "generated "
        f"{len(rows)} mappings "
        f"({sum(not row['key2'] for row in rows)} single, "
        f"{sum(bool(row['key2']) for row in rows)} combos)"
    )


if __name__ == "__main__":
    main()
