#!/usr/bin/env python3
import collections
import csv
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LAYOUT_CSV = ROOT / "data" / "logos_kana_layout.csv"
ROMAJI_CSV = ROOT / "data" / "logos_kana_romaji.csv"

KEYS_HEADER_OUT = ROOT / "include" / "dt-bindings" / "logos_kana" / "keys.h"
QWERTY_OUT = ROOT / "dts" / "behaviors" / "logos_kana_qwerty.dtsi"
PROFILE_OUT = ROOT / "dts" / "behaviors" / "logos_kana_torabo_tsuki_lp.dtsi"
MAP_OUT = ROOT / "src" / "logos_kana_map.inc"

TOTAL_POSITIONS = 66
KANA_TOGGLE_POSITION = 65
ROW_LENGTHS = [12, 12, 14, 14, 14]

EXPECTED_SINGLE_KEYS = 30
EXPECTED_COMBOS = 105
EXPECTED_TOTAL = 135

KEY_POSITIONS = {
    "q": 13,
    "w": 14,
    "e": 15,
    "r": 16,
    "t": 17,
    "y": 18,
    "u": 19,
    "i": 20,
    "o": 21,
    "p": 22,
    "a": 25,
    "s": 26,
    "d": 27,
    "f": 28,
    "g": 29,
    "h": 32,
    "j": 33,
    "k": 34,
    "l": 35,
    ";": 36,
    "z": 39,
    "x": 40,
    "c": 41,
    "v": 42,
    "b": 43,
    "n": 46,
    "m": 47,
    ",": 48,
    ".": 49,
    "/": 50,
}

LAYOUT_KEYCODES = {
    ";": "SEMI",
    ",": "COMMA",
    ".": "DOT",
    "/": "SLASH",
}

ROMAJI_KEYCODES = {
    "-": "MINUS",
    ",": "COMMA",
    ".": "DOT",
}

LAYOUT_KEY_ORDER = [
    "q",
    "w",
    "e",
    "r",
    "t",
    "y",
    "u",
    "i",
    "o",
    "p",
    "a",
    "s",
    "d",
    "f",
    "g",
    "h",
    "j",
    "k",
    "l",
    ";",
    "z",
    "x",
    "c",
    "v",
    "b",
    "n",
    "m",
    ",",
    ".",
    "/",
]


def read_csv(path, expected_headers):
    with path.open(newline="", encoding="utf-8") as file:
        reader = csv.DictReader(file)
        if reader.fieldnames != expected_headers:
            raise ValueError(f"{path}: expected headers {expected_headers}, got {reader.fieldnames}")
        rows = list(reader)

    for index, row in enumerate(rows, start=2):
        if any(value is None for value in row.values()):
            raise ValueError(f"{path}:{index}: malformed row {row}")
        for header in expected_headers:
            if header != "key2" and not row[header]:
                raise ValueError(f"{path}:{index}: {header} is required")
    return rows


def macro_suffix_for_key(key):
    if re.fullmatch(r"[a-z]", key):
        return key.upper()
    return keycode_for_layout_key(key)


def key_define_for_layout_key(key):
    return f"LOGOS_KANA_KEY_{macro_suffix_for_key(key)}"


def binding_define_for_layout_key(key):
    return f"LOGOS_KANA_{macro_suffix_for_key(key)}"


def keycode_for_char(char):
    if re.fullmatch(r"[a-z]", char):
        return char.upper()
    if char in ROMAJI_KEYCODES:
        return ROMAJI_KEYCODES[char]
    raise ValueError(f"Unsupported romaji character: {char!r}")


def keycode_for_layout_key(key):
    if re.fullmatch(r"[a-z]", key):
        return key.upper()
    if key in LAYOUT_KEYCODES:
        return LAYOUT_KEYCODES[key]
    raise ValueError(f"Unsupported layout key: {key!r}")


def validate_unique(rows, key_fn, label):
    duplicates = [item for item, count in collections.Counter(map(key_fn, rows)).items() if count > 1]
    if duplicates:
        raise ValueError(f"Duplicate {label}: {duplicates}")


def load_romaji():
    rows = read_csv(ROMAJI_CSV, ["output", "romaji"])
    validate_unique(rows, lambda row: row["output"], "romaji output")
    romaji = {row["output"]: row["romaji"] for row in rows}
    for output, value in romaji.items():
        for char in value:
            keycode_for_char(char)
    return romaji


def load_layout():
    rows = read_csv(LAYOUT_CSV, ["output", "key1", "key2"])
    validate_unique(rows, lambda row: row["output"], "layout output")
    validate_unique(rows, lambda row: tuple(sorted([row["key1"], row["key2"]])), "layout key combo")

    for index, row in enumerate(rows, start=2):
        for key_name in ["key1", "key2"]:
            key = row[key_name]
            if key and key not in KEY_POSITIONS:
                raise ValueError(f"{LAYOUT_CSV}:{index}: unknown {key_name} {key!r}")

    single_count = sum(not row["key2"] for row in rows)
    combo_count = sum(bool(row["key2"]) for row in rows)
    if len(rows) != EXPECTED_TOTAL or single_count != EXPECTED_SINGLE_KEYS or combo_count != EXPECTED_COMBOS:
        raise ValueError(
            "Unexpected layout counts: "
            f"total={len(rows)}, single={single_count}, combo={combo_count}"
        )
    return rows


def prepare_rows():
    romaji = load_romaji()
    rows = load_layout()

    missing = sorted({row["output"] for row in rows if row["output"] not in romaji})
    if missing:
        raise ValueError(f"Missing romaji mapping for: {', '.join(missing)}")

    for row in rows:
        row["romaji"] = romaji[row["output"]]
    return rows


def write_keys_header():
    lines = [
        "/* Generated by tools/generate_logos_kana_zmk.py. Do not edit manually. */",
        "",
        "#pragma once",
        "",
        "#define LOGOS_KANA_KEY_NONE 0xFF",
        "",
    ]
    for index, key in enumerate(LAYOUT_KEY_ORDER):
        lines.append(f"#define {key_define_for_layout_key(key):<26} {index}")
    lines.extend(["", f"#define LOGOS_KANA_KEY_COUNT {len(LAYOUT_KEY_ORDER)}", ""])
    KEYS_HEADER_OUT.parent.mkdir(parents=True, exist_ok=True)
    KEYS_HEADER_OUT.write_text("\n".join(lines), encoding="utf-8")


def write_qwerty_dtsi():
    lines = [
        "// Generated by tools/generate_logos_kana_zmk.py. Do not edit manually.",
        "",
        "#include <dt-bindings/zmk/keys.h>",
        "#include <dt-bindings/logos_kana/keys.h>",
        "",
    ]
    for key in LAYOUT_KEY_ORDER:
        define = binding_define_for_layout_key(key)
        lines.extend(
            [
                f"#ifndef {define}",
                f"#define {define} &lgk {key_define_for_layout_key(key)} {keycode_for_layout_key(key)}",
                "#endif",
                "",
            ]
        )
    QWERTY_OUT.parent.mkdir(parents=True, exist_ok=True)
    QWERTY_OUT.write_text("\n".join(lines), encoding="utf-8")


def write_profile_dtsi():
    bindings = ["&trans"] * TOTAL_POSITIONS
    for key in LAYOUT_KEY_ORDER:
        bindings[KEY_POSITIONS[key]] = binding_define_for_layout_key(key)
    bindings[KANA_TOGGLE_POSITION] = "LOGOS_KANA_TOGGLE_BINDING"

    offset = 0
    layer_rows = []
    for row_length in ROW_LENGTHS:
        row_bindings = bindings[offset : offset + row_length]
        layer_rows.append(" ".join(f"{binding:<20}" for binding in row_bindings).rstrip())
        offset += row_length

    if offset != TOTAL_POSITIONS:
        raise ValueError(f"ROW_LENGTHS add up to {offset}, expected {TOTAL_POSITIONS}")

    lines = [
        "// Generated by tools/generate_logos_kana_zmk.py. Do not edit manually.",
        "",
        "#ifndef LOGOS_KANA_TOGGLE_BINDING",
        "#define LOGOS_KANA_TOGGLE_BINDING &logos_kana_off",
        "#endif",
        "",
        "#ifndef LOGOS_KANA_LAYER_BINDINGS",
        "#define LOGOS_KANA_LAYER_BINDINGS \\",
    ]
    for index, layer_row in enumerate(layer_rows):
        suffix = " \\" if index < len(layer_rows) - 1 else ""
        lines.append(f"{layer_row}{suffix}")
    lines.extend(["#endif", ""])
    PROFILE_OUT.parent.mkdir(parents=True, exist_ok=True)
    PROFILE_OUT.write_text("\n".join(lines), encoding="utf-8")


def write_map_inc(rows):
    lines = [
        "/* Generated by tools/generate_logos_kana_zmk.py. Do not edit manually. */",
        "",
        "static const struct logos_kana_mapping logos_kana_mappings[] = {",
    ]
    for row in rows:
        key1 = key_define_for_layout_key(row["key1"])
        key2 = key_define_for_layout_key(row["key2"]) if row["key2"] else "LOGOS_KANA_KEY_NONE"
        output = [keycode_for_char(char) for char in row["romaji"]]
        output.append("LOGOS_KANA_OUTPUT_END")
        lines.append(
            f"    {{.key1 = {key1}, .key2 = {key2}, .output = {{{', '.join(output)}}}}},"
            f" /* {row['romaji']} */"
        )
    lines.extend(["};", ""])
    MAP_OUT.parent.mkdir(parents=True, exist_ok=True)
    MAP_OUT.write_text("\n".join(lines), encoding="utf-8")


def main():
    rows = prepare_rows()
    write_keys_header()
    write_qwerty_dtsi()
    write_profile_dtsi()
    write_map_inc(rows)
    print(
        "generated "
        f"{len(rows)} mappings "
        f"({sum(not row['key2'] for row in rows)} single, "
        f"{sum(bool(row['key2']) for row in rows)} combos)"
    )


if __name__ == "__main__":
    main()
